"""Edinburgh Airport (EDI) destinations — May 2026."""

DESTINATIONS = {
    "EDI": {
        "name": "Edinburgh",
        "routes": {
            "ACE": "Lanzarote",
            "AGA": "Agadir",
            "AGP": "Malaga",
            "ALC": "Alicante",
            "AMS": "Amsterdam",
            "ARN": "Stockholm",
            "ATH": "Athens",
            "AYT": "Antalya",
            "BCN": "Barcelona",
            "BER": "Berlin",
            "BFS": "Belfast Intl",
            "BGO": "Bergen",
            "BGY": "Milan Bergamo",
            "BHD": "Belfast City",
            "BHX": "Birmingham",
            "BIO": "Bilbao",
            "BIQ": "Biarritz",
            "BJV": "Bodrum",
            "BLL": "Billund",
            "BLQ": "Bologna",
            "BOD": "Bordeaux",
            "BOH": "Bournemouth",
            "BOJ": "Bourgas",
            "BRI": "Bari",
            "BRS": "Bristol",
            "BRU": "Brussels",
            "BSL": "Basel",
            "BTS": "Bratislava",
            "BUD": "Budapest",
            "BZR": "Beziers",
            "CDG": "Paris CDG",
            "CFU": "Corfu",
            "CGN": "Cologne Bonn",
            "CIA": "Rome Ciampino",
            "CMF": "Chambery",
            "CPH": "Copenhagen",
            "CRL": "Brussels Charleroi",
            "CTA": "Catania",
            "DBV": "Dubrovnik",
            "DLM": "Dalaman",
            "DUB": "Dublin",
            "DUS": "Dusseldorf",
            "EAS": "San Sebastian",
            "EFL": "Kefalonia",
            "EGC": "Bergerac",
            "EXT": "Exeter",
            "FAE": "Faroe Islands",
            "FAO": "Faro",
            "FCO": "Rome",
            "FLR": "Florence",
            "FNC": "Funchal",
            "FRA": "Frankfurt",
            "FUE": "Fuerteventura",
            "GCI": "Guernsey",
            "GDN": "Gdansk",
            "GIB": "Gibraltar",
            "GNB": "Grenoble",
            "GOT": "Gothenburg",
            "GRO": "Girona",
            "GVA": "Geneva",
            "HEL": "Helsinki",
            "HER": "Heraklion",
            "IBZ": "Ibiza",
            "INN": "Innsbruck",
            "IOM": "Isle of Man",
            "IST": "Istanbul",
            "JER": "Jersey",
            "JSI": "Skiathos",
            "JTR": "Santorini",
            "KEF": "Reykjavik",
            "KGS": "Kos",
            "KLX": "Kalamata",
            "KOI": "Kirkwall",
            "KRK": "Krakow",
            "KUN": "Kaunas",
            "LCA": "Larnaca",
            "LCY": "London City",
            "LDY": "Derry",
            "LGW": "London Gatwick",
            "LHR": "London Heathrow",
            "LIS": "Lisbon",
            "LJU": "Ljubljana",
            "LPA": "Gran Canaria",
            "LSI": "Sumburgh",
            "LTN": "London Luton",
            "LUX": "Luxembourg",
            "LYS": "Lyon",
            "MAD": "Madrid",
            "MAH": "Menorca",
            "MLA": "Malta",
            "MRS": "Marseille",
            "MUC": "Munich",
            "MXP": "Milan Malpensa",
            "NAP": "Naples",
            "NBE": "Enfidha",
            "NCE": "Nice",
            "NOC": "Knock",
            "NQY": "Newquay",
            "NTE": "Nantes",
            "OLB": "Olbia",
            "OPO": "Porto",
            "ORK": "Cork",
            "ORY": "Paris Orly",
            "OSL": "Oslo",
            "OTP": "Bucharest",
            "PFO": "Paphos",
            "PIS": "Poitiers",
            "PMI": "Palma",
            "PMO": "Palermo",
            "POZ": "Poznan",
            "PRG": "Prague",
            "PSA": "Pisa",
            "PVK": "Preveza",
            "RAK": "Marrakesh",
            "REU": "Reus",
            "RHO": "Rhodes",
            "RIX": "Riga",
            "RVN": "Rovaniemi",
            "RZE": "Rzeszow",
            "SDR": "Santander",
            "SKG": "Thessaloniki",
            "SNN": "Shannon",
            "SOF": "Sofia",
            "SOU": "Southampton",
            "SPU": "Split",
            "STN": "London Stansted",
            "STR": "Stuttgart",
            "SVQ": "Seville",
            "SYY": "Stornoway",
            "SZG": "Salzburg",
            "TFS": "Tenerife South",
            "TIA": "Tirana",
            "TLL": "Tallinn",
            "TLS": "Toulouse",
            "TRN": "Turin",
            "VCE": "Venice",
            "VIE": "Vienna",
            "VLC": "Valencia",
            "VRN": "Verona",
            "WAW": "Warsaw",
            "WRO": "Wroclaw",
            "ZAD": "Zadar",
            "ZRH": "Zurich",
            "ZTH": "Zakynthos",
        },
    },
}


def get_destinations(airport: str) -> dict:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("routes", {})


def get_airport_name(airport: str) -> str:
    entry = DESTINATIONS.get(airport, {})
    return entry.get("name", airport)
